---
- name: Get ansible_user home directory
  ansible.builtin.shell: 'set -o pipefail && getent passwd "{{ ansible_user }}" | cut -d: -f6'
  register: python_ansible_home_result
  changed_when: false
  when:
    - ansible_os_family == "Debian"
  tags:
    - config-language
    - config-python

- name: Get ansible_user home directory
  ansible.builtin.shell: set -o pipefail && finger "{{ ansible_user }}" | awk '/^Directory/ {print $2}'
  register: python_mac_ansible_home_result
  changed_when: false
  when:
    - ansible_os_family == "Darwin"
  tags:
    - config-language
    - config-python

- name: Set the fact for the other scripts to use
  ansible.builtin.set_fact:
    python_ansible_home: "{{ python_ansible_home_result.stdout }}"
  changed_when: false
  when: python_ansible_home_result.stdout is defined
  tags:
    - config-language
    - config-python

- name: Set the fact for the other scripts to use
  ansible.builtin.set_fact:
    python_ansible_home: "{{ python_mac_ansible_home_result.stdout }}"
  changed_when: false
  when: python_mac_ansible_home_result.stdout is defined
  tags:
    - config-language
    - config-python

- name: Install uv
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      set -e
      curl -LsSf https://astral.sh/uv/install.sh | sh
  tags:
    - config-language
    - config-python
