---
- name: Get ansible_user home directory (Debian)
  ansible.builtin.shell: 'set -o pipefail && getent passwd "{{ ansible_user }}" | cut -d: -f6'
  register: arm64_m4_ansible_home_result_debian
  changed_when: false
  when:
    - ansible_os_family == "Debian"
  tags:
    - config-iot
    - config-arm64-m4

- name: Get ansible_user home directory (Darwin)
  ansible.builtin.shell: set -o pipefail && finger "{{ ansible_user }}" | awk '/^Directory/ {print $2}'
  register: arm64_m4_ansible_home_result_darwin
  changed_when: false
  when:
    - ansible_os_family == "Darwin"
  tags:
    - config-iot
    - config-arm64-m4

- name: Set the fact for the other scripts to use
  ansible.builtin.set_fact:
    arm64_m4_ansible_home: "{{ arm64_m4_ansible_home_result_debian.stdout | default(arm64_m4_ansible_home_result_darwin.stdout | default('')) }}"
  changed_when: false
  when: (arm64_m4_ansible_home_result_debian.stdout is defined) or (arm64_m4_ansible_home_result_darwin.stdout is defined)
  tags:
    - config-iot
    - config-arm64-m4

- name: Get os in lowercase
  ansible.builtin.shell: set -o pipefail && uname | tr '[:upper:]' '[:lower:]'
  register: arm64_m4_os_result
  changed_when: false
  tags:
    - config-iot
    - config-arm64-m4

- name: Get target arch
  ansible.builtin.shell: set -o pipefail && uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/'
  register: arm64_m4_arch_result
  changed_when: false
  tags:
    - config-iot
    - config-arm64-m4

- name: For debian
  ansible.builtin.import_tasks: debian.yml
  when:
    - ansible_os_family == "Debian"

- name: For darwin
  ansible.builtin.import_tasks: darwin.yml
  when:
    - ansible_os_family == "Darwin"
