---
packages_cursor_bin_path: /usr/local/bin/cursor
packages_cursor_icon_path: /usr/local/share/icons/cursor.png

packages_obsidian_version: 1.8.9
packages_obsidian_bin_path: /usr/local/bin/obsidian
packages_obsidian_icon_path: /usr/local/share/icons/obsidian.png
