---
- name: Get ansible_user home directory
  ansible.builtin.shell: 'set -o pipefail && getent passwd "{{ ansible_user }}" | cut -d: -f6'
  register: llvm_ansible_home_result
  changed_when: false
  when:
    - ansible_os_family == "Debian"
  tags:
    - config-language
    - config-llvm

- name: Get ansible_user home directory
  ansible.builtin.shell: set -o pipefail && finger "{{ ansible_user }}" | awk '/^Directory/ {print $2}'
  register: llvm_mac_ansible_home_result
  changed_when: false
  when:
    - ansible_os_family == "Darwin"
  tags:
    - config-language
    - config-llvm

- name: Set the fact for the other scripts to use
  ansible.builtin.set_fact:
    llvm_ansible_home: "{{ llvm_ansible_home_result.stdout }}"
  changed_when: false
  when: llvm_ansible_home_result.stdout is defined
  tags:
    - config-language
    - config-llvm

- name: Set the fact for the other scripts to use
  ansible.builtin.set_fact:
    llvm_ansible_home: "{{ llvm_mac_ansible_home_result.stdout }}"
  changed_when: false
  when: llvm_mac_ansible_home_result.stdout is defined
  tags:
    - config-language
    - config-llvm

- name: Get os in lowercase
  ansible.builtin.shell: set -o pipefail && uname | tr '[:upper:]' '[:lower:]'
  register: llvm_os_result
  changed_when: false
  tags:
    - config-language
    - config-llvm

- name: Get target arch
  ansible.builtin.shell: set -o pipefail && uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/'
  register: llvm_arch_result
  changed_when: false
  tags:
    - config-language
    - config-llvm

- name: For debian
  ansible.builtin.import_tasks: debian.yml
  when:
    - ansible_os_family == "Debian"

- name: For darwin
  ansible.builtin.import_tasks: darwin.yml
  when:
    - ansible_os_family == "Darwin"
