---
galaxy_info:
  author: terakoya76
  description: ESP32 development environment setup
  license: MIT
  min_ansible_version: "2.18"
  standalone: true
dependencies:
  - role: packages
  - role: rust
