---
kubernetes_kustomize_version: 5.0.1
kubernetes_kustomize_path: /usr/local/bin/kustomize

kubernetes_kubeseal_version: 0.20.2
kubernetes_kubeseal_path: /usr/local/bin/kubeseal

kubernetes_stern_path: /usr/local/bin/stern

kubernetes_sops_version: 3.7.3
kubernetes_sops_path: /usr/local/bin/sops

kubernetes_sopsed_path: /usr/local/bin/sopsed

kubernetes_variant_path: /usr/local/bin/variant
